#!/bin/bash -e
pwd

echo "changing to Maxwell server directory"
cd /app/maxwell-server

echo "starting simserver"
python3 simserver.py $NGPUS &> simserver.log &

echo "starting webserver"
python3 webserver.py $PORT  &> webserver.log
