#!/bin/bash -e
pwd

echo "changing to Maxwell server directory"
cd /app

echo "starting simserver"
python3 maxwell-server/simserver.py $NGPUS &> simserver.log &

echo "starting webserver"
python3 maxwell-server/webserver.py $PORT  &> webserver.log
