# build docker image and push to github registry
name: Build and Push Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
      - 'maxwell-server/**'
      - 'maxwell-solver/**'
      - 'requirements.yml'
      - 'README'
      - 'run_docker'
      - 'podman_*'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
      - 'maxwell-server/**'
      - 'maxwell-solver/**'
      - 'requirements.yml'
      - 'README'
      - 'run_docker'
      - 'podman_*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/maxwell-b:${{ github.sha }} 
            ghcr.io/${{ github.repository_owner }}/maxwell-b:latest